apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: registry-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email address used for ACME registration
    email: sunsingerus@gmail.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: sunsingerus-prod

    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx

