apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "registry"
  annotations:
    cert-manager.io/issuer: "registry-prod"
    kubernetes.io/ingress.class: "nginx"
    # This is importnant in order not to hit "413 Request Entity Too Large" reply from Ingress
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    - host: "registry.sunsingerus.com"
      http:
        paths:
          - path: "/"
            backend:
              serviceName: registry-cip
              servicePort: 5000
  tls:
    - hosts:
        - "registry.sunsingerus.com"
      secretName: registry-tls

